### ISSUE TITLE
Error when numpy in 1.19.4

### ISSUE THREAD

**Issue by Keycatowo** [allenyllee/DataTag_helper#1]
When I was trying to run the `AI_Clerk_helper.py`, I got something error.
Here is the error message:
```bash
AI_Clerk_helper>python AI_Clerk_helper.py
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "AI_Clerk_helper.py", line 25, in <module>
    import pandas as pd
  File "A:\code\Miniconda\envs\AI_Clerk_helper\lib\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)
  File "A:\code\Miniconda\envs\AI_Clerk_helper\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "A:\code\Miniconda\envs\AI_Clerk_helper\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('A:\\code\\Miniconda\\envs\\AI_Clerk_helper\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

After some search, I found that the problem is cause to the numpy version, install the numpy in 1.19.3 will fix the problem.
```bash
pip install numpy==1.19.3
```

see more: [stackoverflow：How do you fix “runtimeError: package fails to pass a sanity check” for numpy and pandas?](https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an)

**Comment by allenyllee** [comment]
Add below to requirements.txt

```
numpy==1.19.3; platform_system == "Windows"
numpy>=1.19.4; platform_system == "Linux"
```

you can check platform_system by following code:

```
import platform
platform.system()
```

see: https://www.python.org/dev/peps/pep-0508/#environment-markers
